sudo: required

language: php

php:
  - '7.2'

services:
  - docker

before_script: composer install

script:
  - docker build -t tec/internweb .
  - docker tag tec/internweb node2.didithilmy.com/tec/internweb
  - docker push node2.didithilmy.com/tec/internweb
